version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    image: jordanbreen28/golang-auth:dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/app
    depends_on:
      - postgres
  postgres:
    image: postgres:16.0-bullseye
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
